using Godot;
using Cave.Core;

namespace CozyCave;
public partial class Main
{
    private async Task Frames(int count = 8)
    { for (int i = 0; i < count; i++) await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame); }
    private async Task RunSmokeTests(string output)
    {
        var results = new List<string>();
        void Check(bool ok, string label) { results.Add((ok ? "PASS " : "FAIL ") + label); GD.Print(results[^1]); }
        try
        {
            System.IO.Directory.CreateDirectory(output);
            await Frames(20);
            player.Position=new Vector3(1,1,5);camera.LookAt(new Vector3(-7,3,-2));await Frames(30);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"cozy-remodel.png"));

            Check(WithinWorld(new Vector3(35,70,-35)) && WithinWorld(new Vector3(0,-30,0)) && !WithinWorld(new Vector3(0,97,0)),"Valley permits wide, high and underground builds within finite bounds");
            Check(!terrain.Values.Any(t=>t.Position.X==9 && t.Position.Z==-3 && t.Position.Y>=0 && t.Position.Y<3),"East doorway removes cave wall blocks for walking outside");
            var miningCell=new Vector3I(18,-10,0);var untouchedKind=ValleyKind(miningCell+Vector3I.Right);
            Check(ValleyKind(miningCell)=="stone" && !CanPickUp(ValleyId(new(18,ValleyBottom-1,0))),"Underground is mineable stone above protected bedrock");
            EnsureValley(new Vector3(18,-10,0),true);PickUpObject(ValleyId(miningCell));
            Check(ValleyKind(miningCell)==null && ValleyKind(miningCell+Vector3I.Right)==untouchedKind && store.Load().RemovedTerrain.Contains(ValleyId(miningCell)),"Mining underground removes only selected cell and persists its edit");
            var valleyDrop=state.Drops.Last();CollectDrop(valleyDrop);
            BeginPlacement("stone",null);placementPosition=new Vector3(18,-10,0);placementValid=true;Place();CancelPlacement();
            Check(state.BuildingBlocks.Any(b=>b.X==18 && b.Y==-10),"Building below cave floor persists a real block");
            var undergroundBlock=state.BuildingBlocks.Last();state.BuildingBlocks.Remove(undergroundBlock);RemovePlacedObject("$block:"+undergroundBlock.Id);
            int radiusBefore=WorldRadius;var oldGround=ValleyKind(new(20,-1,0));state.ValleyRadius+=16;
            Check(WorldRadius==radiusBefore+16 && ValleyKind(new(20,-1,0))==oldGround,"Expanding world border preserves existing terrain");state.ValleyRadius=radiusBefore;
            ToggleFlight();Check(flying && store.Load().Flying,"Creative flight toggle persists");ToggleFlight();
            player.Position=new Vector3(18,-12,0);Save();Check(store.Load().Player[1]<0,"Underground player position survives saving");
            ReturnHome();Check(player.Position==new Vector3(0,2,4),"Home shortcut safely returns from underground");
            player.Position=new Vector3(17,16,7);EnsureValley(player.Position,true);await Frames(3);float flightStart=player.Position.Y;
            Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.Space,Keycode=Key.Space,Pressed=true});await Frames(16);Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.Space,Keycode=Key.Space,Pressed=false});
            results.Add($"Flight rise: {flightStart} to {player.Position.Y}, walking={walking}, flying={flying}");
            Check(player.Position.Y>flightStart+.3f,"Flight Space rises through actual movement input");float flightHigh=player.Position.Y;
            Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.Ctrl,Keycode=Key.Ctrl,Pressed=true});await Frames(16);Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.Ctrl,Keycode=Key.Ctrl,Pressed=false});
            Check(player.Position.Y<flightHigh-.3f,"Flight Ctrl descends through actual movement input");
            player.Position=new Vector3(21,12,5);EnsureValley(player.Position,true);camera.LookAt(new Vector3(0,0,-24));await Frames(30);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"expandable-valley.png"));
            player.Position=new Vector3(11,.05f,-3);EnsureValley(player.Position,true);camera.LookAt(new Vector3(5,1,-3));await Frames(5);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"valley-entrance.png"));
            player.Rotation=Vector3.Zero;Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.A,Pressed=true});await Frames(40);Input.ParseInputEvent(new InputEventKey {PhysicalKeycode=Key.A,Pressed=false});
            Check(player.Position.X<8,"Player can cross the old cave boundary through the entrance");
            ReturnHome();ToggleFlight();await Frames(20);

            Release(false);hidden=true;ResumeCaveFocus();Check(walking && !hidden && !backgroundApp,"Returning focus resumes the cave immediately without another click");
            Release();ResumeCaveFocus();Check(!walking,"Explicit hold-Escape release remains released");
            Enter();Release(false);ShowNotebook();ResumeCaveFocus();Check(!walking && panel!=null,"Returning to an open notebook keeps pointer interaction");ClosePanel();
            Check(Descendants(world).Any(n=>n.Name=="DeskNotebook"),"Writing desk has a targetable notebook");
            Check(Descendants(Descendants(world).First(n=>n.Name=="DeskNotebook")).OfType<MeshInstance3D>().Count(n=>n.Mesh is BoxMesh)>=10,"Desk book has three-dimensional covers, pages, spine and quill");
            ShowNotebook();await Frames(3);
            Descendants(panel!).OfType<TextEdit>().Single(n=>n.Name=="NoteText").Text="Remember the rainy valley\nQuick notes: caf\u00e9, \u65e5\u672c\u8a9e";
            Descendants(panel!).OfType<TextEdit>().Single(n=>n.Name=="NoteText").EmitSignal(TextEdit.SignalName.TextChanged);UpdateNotebook(1);await Frames(3);
            Check(store.Load().Notebook[0].Text.Contains("\u65e5\u672c\u8a9e"),"Notebook autosaves multiline Unicode notes");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"notebook-notes.png"));
            notebookChecklist=true;state.Notebook[0].Tasks.Add(new NoteTask {Text="Organize project files"});ShowNotebook();await Frames(3);
            Descendants(panel!).OfType<CheckBox>().Single(n=>n.Name=="NoteCheck").ButtonPressed=true;
            ClosePanel();ShowNotebook();await Frames(3);
            Check(store.Load().Notebook[0].Tasks[0].Done && Descendants(panel!).OfType<CheckBox>().Single(n=>n.Name=="NoteCheck").ButtonPressed,"Checklist completion survives save and reopen");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"notebook-checklist.png"));
            Descendants(panel!).OfType<Button>().Single(n=>n.Text=="+ Page").EmitSignal(Godot.Button.SignalName.Pressed);
            Check(state.Notebook.Count==2 && notebookPage==1 && state.Notebook[0].Text.StartsWith("Remember"),"Adding notebook pages preserves existing notes and tasks");
            ClosePanel();notebookChecklist=false;
            var deskBook=state.Decorations.Single(d=>d.Kind=="writable_book");
            PickUpObject("$decor:"+deskBook.Id);
            Check(deskBook.Carried && state.Drops.Any(d=>d.ItemId==deskBook.Id),"Book and Quill becomes a collectible item drop");
            CollectDrop(state.Drops.Single(d=>d.ItemId==deskBook.Id));
            Check(ResolveSupply(deskBook.Id)?.Kind=="writable_book","Collected book can be equipped from inventory");
            BeginPlacement("writable_book",deskBook.Id);
            player.Position=new Vector3(2,.08f,4);player.Rotation=Vector3.Zero;await Frames(3);camera.LookAt(new Vector3(2.38f,1.01f,5.7f));
            _UnhandledInput(new InputEventMouseButton {ButtonIndex=MouseButton.Right,Pressed=true});
            Check(panel==null && !deskBook.Carried && Math.Abs(deskBook.Y-1.02f)<.08f,"Ordinary right-click ray places collected book on the desk without opening notes");
            Check(deskBook.X==2 && deskBook.Z==6,"Book aimed near desk edge snaps to block center");
            CancelPlacement();
            Check(!deskBook.Carried && state.Notebook[0].Text.StartsWith("Remember"),"Placing the book again retains its notes");
            player.Position=new Vector3(2,.08f,3);camera.LookAt(new Vector3(2,1.4f,6));await Frames(8);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"writing-desk.png"));
            using (var atlas = CubeMaterial("stone").AlbedoTexture.GetImage()) Check(atlas.GetPixel(8,8).A > .99f, "Vanilla stone atlas has opaque rendered pixels");
            Check(player.IsOnFloor(), "Player settles onto cave floor");
            Check(new[]{"dark_oak_stairs","spruce_slab","spruce_trapdoor","red_carpet","brown_carpet","chain","campfire","stone_brick_stairs","spruce_fence"}.All(k=>ShapedMesh(k).GetSurfaceCount()>0),"All nine furnishing types load their vanilla model geometry");
            Check(modelBoxes["red_carpet"].Max(b=>b.Size.Y)==1f/16,"Carpet collision is one pixel high");
            Check(modelBoxes["dark_oak_stairs"].Count==2,"Stairs use two half-block collision elements");
            Check(terrain.Values.Any(t=>t.Kind=="campfire") && terrain.Values.Any(t=>t.Kind=="bookshelf"),"The lounge contains a campfire hearth and bookshelves");
            player.Position=new Vector3(2,.08f,4);player.Rotation=Vector3.Zero;camera.LookAt(new Vector3(-5,2,-1));await Frames(12);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"hearth-lounge.png"));
            player.Position=new Vector3(-5,.08f,0);camera.LookAt(new Vector3(-8,.7f,0));await Frames(12);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"hearth-detail.png"));
            player.Position=new Vector3(0,1,5);player.Rotation=Vector3.Zero;camera.Rotation=Vector3.Zero;await Frames(12);
            BeginPlacement("dark_oak_stairs",null);player.RotationDegrees=new Vector3(0,90,0);
            placementPosition=new Vector3(3,0,5);placementValid=true;Place();
            var facingBlock=state.BuildingBlocks.Last();
            Check(facingBlock.Rotation==180 && placedNodes["$block:"+facingBlock.Id].RotationDegrees.Y==180,"Placed stair follows current facing in both visual and saved state");
            state.BuildingBlocks.Remove(facingBlock);RemovePlacedObject("$block:"+facingBlock.Id);CancelPlacement();player.Rotation=Vector3.Zero;
            Release(false);Check(backgroundApp && !walking && Input.MouseMode==Input.MouseModeEnum.Visible,"App handoff releases input without requesting desktop attachment");
            Enter();Check(!backgroundApp,"Clicking back into the cave resumes normal entry");Release();
            Check(cat!=null && cat.IsOnFloor(),"Cat settles on cave floor");
            Check(cat!.CollisionLayer==8 && (player.CollisionMask&8)==0,"Cat does not block player movement");
            cat.Position=new Vector3(0,.1f,3);cat.RotationDegrees=new Vector3(0,20,0);ToggleCatSit();await Frames(10);
            Check(state.CatSitting && store.Load().CatSitting,"Right-click cat sitting preference persists");
            player.Position=new Vector3(0,.1f,5);camera.LookAt(cat.Position+Vector3.Up*.45f);Enter();await Frames(12);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"cat.png"));
            ToggleCatSit();Check(!state.CatSitting,"Right-click releases cat to roam");camera.Rotation=Vector3.Zero;
            var obstacle=new BuildingBlock {Kind="stone",X=3,Y=0,Z=4};state.BuildingBlocks.Add(obstacle);CreateBuildingBlock(obstacle);await Frames(8);
            cat.Position=new Vector3(2,.02f,4);catDestination=new Vector3(4,0,4);catRest=0;catDecision=100;PlanCatRoute();
            Check(catRoute.Count>0 && catRoute.Any(p=>Math.Abs(p.Z-4)>.4f),"Cat plans a route around furniture instead of straight into it");
            var catStart=cat.Position;await Frames(100);Check(cat.Position.DistanceTo(catStart)>.35f,"Cat makes progress along obstacle detour");
            state.BuildingBlocks.Remove(obstacle);RemovePlacedObject("$block:"+obstacle.Id);catRoute.Clear();state.CatSitting=true;cat.Position=new Vector3(-6,.1f,6);
            ReceiveApps(System.Text.Json.JsonSerializer.SerializeToElement(new[]{new {Id="group-a",Name="Editor one",Path="editor.exe",Pinned=false,Windows=1},new {Id="group-b",Name="Editor two",Path="editor.exe",Pinned=false,Windows=1}}));
            Check(quickApps.Count==1 && quickApps[0].WindowIds?.Length==2,"Multiple windows are grouped into one app slot");
            var hotbarApps=Enumerable.Range(0,12).Select(i=>new {Id="quick-"+i,Name="App "+i,Path="",Pinned=false,Windows=1}).ToArray();
            ReceiveApps(System.Text.Json.JsonSerializer.SerializeToElement(hotbarApps));
            int savedBlock=state.SelectedSlot;ToggleDesktopHotbar();SelectDesktopSlot(9);await Frames(8);
            Check(desktopHotbarActive && desktopSelection==9 && state.SelectedSlot==savedBlock,"App hotbar pages without changing selected building slot");
            Enter();PollMouseActions(false,false);_UnhandledInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=true});
            Check(backgroundApp && !walking,"Left-click selected app hands focus to Windows instead of opening close menu");
            Enter();PollMouseActions(false,false);_UnhandledInput(new InputEventMouseButton {ButtonIndex=MouseButton.Right,Pressed=true});
            Check(!backgroundApp,"Right-click selected app does not launch it");
            Check(panel?.Name=="AppContextMenu" && !walking,"In-game close menu stays inside renderer with mouse released");
            ResumeCaveFocus();await Frames(3);
            Check(panel?.Name=="AppContextMenu" && !walking && Input.MouseMode==Input.MouseModeEnum.Visible,"Focus return cannot dismiss close menu or recapture its pointer");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"app-close-menu.png"));
            var appCloseButton=Descendants(panel!).OfType<Button>().Single(b=>b.Name=="CloseAppWindows");
            var appClosePoint=appCloseButton.GetGlobalRect().GetCenter();
            GetViewport().PushInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=true,Position=appClosePoint,GlobalPosition=appClosePoint},true);await Frames(2);
            Check(panel!=null,"Close menu survives mouse-down until button release");
            GetViewport().PushInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=false,Position=appClosePoint,GlobalPosition=appClosePoint},true);await Frames(2);
            Check(panel==null && walking,"Real close-button click completes and resumes cave controls");

            SelectDesktopSlot(-1);Check(desktopSelection==11,"App hotbar wheel selection wraps across pages");
            await Frames(8);GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"two-row-hotbar.png"));
            ToggleDesktopHotbar();Check(!desktopHotbarActive && state.SelectedSlot==savedBlock,"Backtick switching restores building hotbar selection");
            var originalJukebox=terrain.Single(t=>t.Value.Kind=="jukebox");
            string jukeboxId="$terrain:"+originalJukebox.Key;
            Check(CanPickUp(jukeboxId),"Original jukebox is mineable");
            PickUpObject(jukeboxId);
            var jukeboxDrop=state.Drops.Single(d=>d.Kind=="jukebox");
            Check(state.RemovedTerrain.Contains(originalJukebox.Key) && !state.Settings.MusicEnabled,"Breaking jukebox persists removal and stops playback");
            CollectDrop(jukeboxDrop);BeginPlacement("jukebox",null);placementPosition=new Vector3(4,0,4);placementValid=true;Place();CancelPlacement();
            var newJukebox=state.BuildingBlocks.Last();Check(InteractBlock("$block:"+newJukebox.Id),"Replaced jukebox opens music controls");ClosePanel();
            state.BuildingBlocks.Remove(newJukebox);state.RemovedTerrain.Remove(originalJukebox.Key);BuildWorld();
            await LoadMinecraftMusic();
            Check(state.Settings.Playlist.Count==3 && music.Playing && playingPath!=null,"Three verified original Minecraft tracks download and play");
            music.Stop();state.Settings.MusicEnabled=false;state.Settings.Playlist.Clear();playingPath=null;
            string photoPath=System.IO.Path.GetFullPath(System.IO.Path.Combine(output,"test-photo.png"));
            using(var photo=Image.CreateEmpty(128,64,false,Image.Format.Rgba8)) {photo.Fill(new Color("498fbb"));photo.FillRect(new Rect2I(0,32,128,32),new Color("507b43"));photo.SavePng(photoPath);}
            var photoBytes=System.IO.File.ReadAllBytes(photoPath);
            var photoLink=library.Add(photoPath,"inbox");Changed();ShowChest("inbox");await Frames(8);
            var photoDrop=Descendants(panel!).OfType<PictureDropButton>().Single();
            var photoPayload=new Godot.Collections.Dictionary {{"path",photoPath},{"container","inbox"},{"link",""}};
            Check(photoDrop._CanDropData(Vector2.Zero,photoPayload),"Chest frame action accepts dragged image files");
            Check(!photoDrop._CanDropData(Vector2.Zero,new Godot.Collections.Dictionary {{"path","notes.txt"}}),"Frame drop target rejects non-image files");
            var linksBefore=state.Links.Select(l=>(l.Id,l.ChestId,l.Path)).ToArray();
            var photoSource=Descendants(panel!).OfType<ChestSlot>().First(slot=>slot.Entry?.Path==photoPath);
            var photoStart=photoSource.GetGlobalRect().GetCenter();var photoEnd=photoDrop.GetGlobalRect().GetCenter();
            GetViewport().PushInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=true,Position=photoStart,GlobalPosition=photoStart},true);await Frames(2);
            GetViewport().PushInput(new InputEventMouseMotion {Position=photoStart+new Vector2(20,0),GlobalPosition=photoStart+new Vector2(20,0),Relative=new Vector2(20,0),ButtonMask=MouseButtonMask.Left},true);await Frames(2);
            GetViewport().PushInput(new InputEventMouseMotion {Position=photoEnd,GlobalPosition=photoEnd,Relative=photoEnd-photoStart,ButtonMask=MouseButtonMask.Left},true);await Frames(2);
            GetViewport().PushInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=false,Position=photoEnd,GlobalPosition=photoEnd},true);await Frames(3);
            var madeFrame=state.Decorations.Last();
            Check(madeFrame.Carried && madeFrame.PicturePath==photoPath && movingId==madeFrame.Id && panel==null,"Dragging a photo creates and equips a placeable frame");
            await Frames(5);GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"held-photo-frame.png"));
            Check(hand!.HasNode("Photo") && hotbarSlots[state.SelectedSlot].Icon==LoadPicture(photoPath),"Held frame and hotbar show the actual photo");
            Check(state.Links.Select(l=>(l.Id,l.ChestId,l.Path)).SequenceEqual(linksBefore),"Framing a photo preserves every chest link");
            player.Position=new Vector3(7,.1f,1);camera.LookAt(new Vector3(9,1.5f,1));await Frames(5);UpdatePlacement();
            Check(placementValid,"Photo frame finds a valid wall through normal aiming");Place(true);CancelPlacement();
            Check(!madeFrame.Carried && placedNodes["$decor:"+madeFrame.Id].HasNode("Photo"),"Right-click placement hangs the framed image in the world");
            PickUpObject("$decor:"+madeFrame.Id);var madeDrop=state.Drops.Single(d=>d.ItemId==madeFrame.Id);
            Check(dropNodes[madeDrop.Id].Visual.HasNode("Photo"),"Collected miniature frame keeps its visible photo");CollectDrop(madeDrop);
            Check(store.Load().Decorations.Single(d=>d.Id==madeFrame.Id).PicturePath==photoPath,"Photo-created frame persists its image link after collection");
            var photoDesk=new BuildingBlock {Kind="spruce_planks",X=2,Y=0,Z=2};state.BuildingBlocks.Add(photoDesk);CreateBuildingBlock(photoDesk);await Frames(3);
            BeginPlacement("item_frame",madeFrame.Id);player.Position=new Vector3(2,.08f,4);player.Rotation=Vector3.Zero;camera.LookAt(new Vector3(2.3f,1,2.3f));await Frames(5);Place(true);CancelPlacement();
            Check(!madeFrame.Carried && madeFrame.TabletopFrame && madeFrame.X==2 && madeFrame.Z==2 && Math.Abs(madeFrame.Y-1.02f)<.05f,"Aiming at a block top places a centered standing photo frame");
            Check(placedNodes["$decor:"+madeFrame.Id].HasNode("StandingFrame/Photo") && store.Load().Decorations.Single(d=>d.Id==madeFrame.Id).TabletopFrame,"Tabletop photo visual and placement mode persist");
            await Frames(5);GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"tabletop-photo.png"));
            PickUpObject("$decor:"+madeFrame.Id);CollectDrop(state.Drops.Single(d=>d.ItemId==madeFrame.Id));
            BeginPlacement("item_frame",madeFrame.Id);player.Position=new Vector3(7,.1f,1);camera.LookAt(new Vector3(9,1.5f,1));await Frames(5);Place(true);CancelPlacement();
            Check(!madeFrame.Carried && !madeFrame.TabletopFrame && madeFrame.PicturePath==photoPath,"A collected tabletop frame can hang on a wall with the same photo");
            state.BuildingBlocks.Remove(photoDesk);RemovePlacedObject("$block:"+photoDesk.Id);

            state.Decorations.Remove(madeFrame);library.Remove(photoLink.Id);CancelPlacement();BuildWorld();

            state.Supplies["item_frame"]=1;BeginPlacement("item_frame",null);placementPosition=new Vector3(0,1,2);placementRotation=180;placementValid=true;Place();CancelPlacement();
            var pictureFrame=state.Decorations.Last();string pictureId="$decor:"+pictureFrame.Id;SetFramePicture(pictureId,photoPath);ClosePanel();
            Check(placedNodes[pictureId].HasNode("Photo"),"Item frame displays selected photo");
            player.Position=new Vector3(0,1,5);camera.Rotation=Vector3.Zero;Enter();await Frames(12);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"picture-frame.png"));
            PickUpObject(pictureId);var pictureDrop=state.Drops.Single(d=>d.ItemId==pictureFrame.Id);CollectDrop(pictureDrop);
            BeginPlacement("item_frame",pictureFrame.Id);placementPosition=new Vector3(1,1,2);placementRotation=180;placementValid=true;Place();CancelPlacement();
            Check(pictureFrame.PicturePath==photoPath && !pictureFrame.Carried && store.Load().Decorations.Single(d=>d.Id==pictureFrame.Id).PicturePath==photoPath,"Collected and replaced frame preserves saved photo link");
            Check(photoBytes.SequenceEqual(System.IO.File.ReadAllBytes(photoPath)) && LoadPicture(photoPath+".missing")==null,"Photo source unchanged and missing photo handled");
            state.Decorations.Remove(pictureFrame);BuildWorld();
            Check(catalogTextures.Count>350,"Workbench imports more than 350 vanilla cube blocks");
            ShowWorkbench();await Frames(8);
            Check(!Descendants(panel!).Any(s=>s.Name.ToString().StartsWith("CraftInput")),"Workbench opens without unused crafting slots");
            Check(Descendants(panel!).Any(s=>s.Name=="BlockCatalog"),"Workbench opens directly to block catalog");
            var blockSearch=Descendants(panel!).OfType<LineEdit>().Single(e=>e.Name=="BlockSearch");blockSearch.Text="diamond_block";blockSearch.EmitSignal(LineEdit.SignalName.TextChanged,blockSearch.Text);await Frames(10);
            var diamondSlot=Descendants(panel!).OfType<ChestSlot>().Single(s=>s.BuildKind=="diamond_block");
            var activePanel=panel;diamondSlot._GuiInput(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=true});
            Check(panel==activePanel,"Pressing a block leaves the screen open to start dragging");
            var inventoryTarget=Descendants(panel!).OfType<ChestSlot>().Single(s=>s.Name=="CatalogInventory4");
            var blockPayload=new Godot.Collections.Dictionary {{"buildkey",diamondSlot.BuildDragKey!}};
            Check(inventoryTarget._CanDropData(Vector2.Zero,blockPayload),"Inventory accepts catalog block drags");
            inventoryTarget._DropData(Vector2.Zero,blockPayload);
            Check(BuildingItems()[4].Kind=="diamond_block","Catalog drop places the block stack in the chosen inventory slot");
            string? beforeSwap=state.BuildingSlots[4];DropBuildingItem("$slot:4",7);Save();
            Check(store.Load().BuildingSlots[7]==beforeSwap,"Inventory drag rearrangement persists after saving");
            string? oldBarItem=state.Hotbar[2];int totalBeforeSwap=SupplyItems().Sum(i=>i.Count);
            var barTarget=Descendants(panel!).OfType<ChestSlot>().Single(s=>s.Name=="CatalogHotbar2");barTarget._DropData(Vector2.Zero,new Godot.Collections.Dictionary {{"buildkey","$slot:7"}});
            Check(state.Hotbar[2]=="diamond_block","Inventory stacks drag onto hotbar without closing catalog");            Check((BuildingItems()[7].Id??BuildingItems()[7].Kind)==oldBarItem && SupplyItems().Sum(i=>i.Count)==totalBeforeSwap,"Inventory-to-hotbar swaps the displaced item without copying supplies");
            Check(!state.BuildingSlots.Contains(state.HotbarStacks[2]),"A hotbar stack is absent from storage inventory");
            DropBuildingItem("$hotbar:2",7);Check(state.Hotbar[2]==oldBarItem && BuildingItems()[7].Kind=="diamond_block","Hotbar-to-inventory drag swaps back");
            DropHotbarItem("$slot:7",2);Save();Check(store.Load().HotbarStacks.SequenceEqual(state.HotbarStacks),"Owned hotbar stacks survive save/load");
            int diamonds=state.Supplies.GetValueOrDefault("diamond_block");diamondSlot.Activated!(MouseButton.Left,false,false);
            Check(state.Supplies["diamond_block"]==diamonds+64,"Workbench search retrieves a stack of the selected block");await Frames(3);
            var dragSource=Descendants(panel!).OfType<ChestSlot>().Single(s=>s.Name=="CatalogInventory7");
            var dragTarget=Descendants(panel!).OfType<ChestSlot>().Single(s=>s.Name=="CatalogInventory6");
            string draggedKind=BuildingItems()[7].Kind;
            var dragFrom=dragSource.GetGlobalRect().GetCenter();var dragTo=dragTarget.GetGlobalRect().GetCenter();
            GetViewport().PushInput(new InputEventMouseMotion {Position=dragFrom,GlobalPosition=dragFrom},true);
            GetViewport().PushInput(new InputEventMouseButton {Position=dragFrom,GlobalPosition=dragFrom,ButtonIndex=MouseButton.Left,Pressed=true,ButtonMask=MouseButtonMask.Left},true);await Frames(2);
            GetViewport().PushInput(new InputEventMouseMotion {Position=dragTo,GlobalPosition=dragTo,Relative=dragTo-dragFrom,ButtonMask=MouseButtonMask.Left},true);await Frames(3);
            GetViewport().PushInput(new InputEventMouseButton {Position=dragTo,GlobalPosition=dragTo,ButtonIndex=MouseButton.Left,Pressed=false},true);await Frames(3);
            Check(panel==activePanel && BuildingItems()[6].Kind==draggedKind,"Real press-drag-release moves inventory blocks without equipping or closing");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"workbench.png"));
            if(diamonds==0) state.Supplies.Remove("diamond_block");else state.Supplies["diamond_block"]=diamonds;
            ClosePanel();
            BeginPlacement("spruce_trapdoor",null);placementPosition=new Vector3(3,0,6);placementValid=true;Place();CancelPlacement();
            var trapdoor=state.BuildingBlocks.Last();Check(!trapdoor.Active,"Newly placed trapdoors start closed");
            Check(InteractBlock("$block:"+trapdoor.Id) && trapdoor.Active,"A newly placed trapdoor opens on right-click");
            Check(InteractBlock("$block:"+trapdoor.Id) && !trapdoor.Active && !store.Load().BuildingBlocks.Single(b=>b.Id==trapdoor.Id).Active,"Trapdoor closes and persists its state");
            Check(modelBoxes["spruce_trapdoor_closed"].Max(b=>b.Size.Y)==3f/16,"Closed trapdoor uses horizontal collision");
            Check(InteractBlock("$block:"+trapdoor.Id) && trapdoor.Active,"Trapdoor reopens with right-click interaction");
            state.BuildingBlocks.Remove(trapdoor);BuildWorld();
            ReceiveApps(System.Text.Json.JsonSerializer.SerializeToElement(new[]{new {Id="test-window",Name="Test editor",Path=System.IO.Path.Combine(System.Environment.SystemDirectory,"notepad.exe"),Pinned=false,Windows=1}}));
            showOpenApps=true;ShowApps();await Frames(10);
            Check(Descendants(panel!).OfType<ChestSlot>().Count()==9 && Descendants(panel!).OfType<ChestSlot>().Any(s=>s.Running),"App hotbar displays nine slots and a running-window marker");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"app-hotbar.png"));ClosePanel();
            var source = System.IO.Path.Combine(output, "fixtures"); System.IO.Directory.CreateDirectory(source);
            var nested = System.IO.Path.Combine(source, "Project notes"); System.IO.Directory.CreateDirectory(nested);
            System.IO.Directory.CreateDirectory(System.IO.Path.Combine(source, "00 Folder"));
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(source, "00 Cave.png"));
            System.IO.File.WriteAllText(System.IO.Path.Combine(source, "00 Document.pdf"), "shell-icon fixture");
            for (int i = 0; i < 65; i++) System.IO.File.WriteAllText(System.IO.Path.Combine(source, $"Document {i:00}.txt"), "fixture");
            System.IO.File.WriteAllText(System.IO.Path.Combine(nested, "Inside.txt"), "nested fixture");
            foreach (var path in System.IO.Directory.EnumerateFileSystemEntries(source)) library.Add(path, "inbox");
            library.Add(System.IO.Path.Combine(source, "Missing file.pdf"), "inbox");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "world.png"));
            ShowChest("inbox"); await Frames(30);
            Check(panel != null && openedChest == "inbox" && !walking, "Chest opens into pointer-driven inventory");
            Check(lids["inbox"].Rotation.X < -1, "Chest lid animates open");
            var slots = Descendants(panel!).OfType<ChestSlot>().ToArray();
            Check(slots.Length == 63 && slots.Count(s => s.Container == LinkLibrary.Inventory) == 36, "Classic chest has 27 chest slots plus 36 carried-file slots");
            Check(slots.Count(s => s.Entry != null && s.TooltipText.Contains(s.Entry.Name)) == 27, "Filenames remain accessible in slot tooltips");
            var iconDeadline = DateTime.UtcNow.AddSeconds(8);
            while (DateTime.UtcNow < iconDeadline)
            {
                slots = Descendants(panel!).OfType<ChestSlot>().ToArray();
                if (slots.Count(s => s.Entry != null && s.Icon != null) == 27) break;
                await Frames(6);
            }
            results.Add($"Shell images visible: {slots.Count(s => s.Icon != null)}; extracted: {shellImagesLoaded}");
            Check(slots.Count(s => s.Entry != null && s.Icon != null) == 27, "Windows Shell images populate every occupied file slot");
            var folderImage = await shellImages.Get(nested);
            Check(folderImage != null && folderImage.Rgba.Any(b => b != 0), "Folder image comes from Windows Shell");
            var desktopAudit = new List<string>();
            foreach(var desktopRoot in new[]{System.Environment.GetFolderPath(System.Environment.SpecialFolder.DesktopDirectory),System.Environment.GetFolderPath(System.Environment.SpecialFolder.CommonDesktopDirectory)})
            foreach(var entry in files.List(desktopRoot))
            {
                var imageTask=shellImages.Get(entry.Path);
                var deadline=DateTime.UtcNow.AddSeconds(3);
                while(!imageTask.IsCompleted && DateTime.UtcNow<deadline) await Frames(2);
                var pixels=imageTask.IsCompleted?await imageTask:null;
                desktopAudit.Add((pixels!=null?"IMAGE ":"UNAVAILABLE ")+entry.Path);
            }
            System.IO.File.WriteAllLines(System.IO.Path.Combine(output,"desktop-images.txt"),desktopAudit);
            Check(desktopAudit.All(line=>line.StartsWith("IMAGE ")),"Windows icons extracted for every real Desktop item (read-only audit)");
            var fixtureLinks=state.Links.ToArray();state.Links.Clear();
            foreach(var line in desktopAudit.Where(l=>l.StartsWith("IMAGE "))) library.Add(line[6..],"inbox");
            ShowChest("inbox");await Frames(150);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"desktop-icons.png"));
            state.Links.Clear();state.Links.AddRange(fixtureLinks);ShowChest("inbox");await Frames(20);
            slots=Descendants(panel!).OfType<ChestSlot>().ToArray();
            var chestSearch=Descendants(panel!).OfType<LineEdit>().Single(e=>e.Name=="ChestSearch");
            chestSearch.Text="Document 64";chestSearch.EmitSignal(LineEdit.SignalName.TextChanged,chestSearch.Text);await Frames(15);
            Check(Descendants(panel!).OfType<ChestSlot>().Count(s=>s.Container=="inbox" && s.Entry!=null)==1 && Descendants(panel!).OfType<ChestSlot>().Any(s=>s.Entry?.Name=="Document 64.txt"),"Chest search reaches files beyond the first page");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"chest-search.png"));
            chestSearch.Text="nothing-matches-this-name";chestSearch.EmitSignal(LineEdit.SignalName.TextChanged,chestSearch.Text);await Frames(15);
            Check(!Descendants(panel!).OfType<ChestSlot>().Any(s=>s.Container=="inbox" && s.Entry!=null),"Search clears stale slots when there are no matches");
            chestSearch.Text="";chestSearch.EmitSignal(LineEdit.SignalName.TextChanged,chestSearch.Text);await Frames(15);slots=Descendants(panel!).OfType<ChestSlot>().ToArray();
            var selectedSlot = slots.First(s => s.Entry != null);
            selectedSlot.Activated!(MouseButton.Left, false, false);
            Check(heldItem != null, "Click picks up an item visually without changing the original");
            selectedSlot.Activated!(MouseButton.Left, false, true);
            Check(state.Links.Any(l => l.ChestId == LinkLibrary.Inventory), "Shift-click carries the file separately from building supplies");
            await Frames(12);
            var carriedLink = state.Links.First(l => l.ChestId == LinkLibrary.Inventory);
            ShowChest("projects");await Frames(12);
            var carriedSlot=Descendants(panel!).OfType<ChestSlot>().First(s=>s.Container==LinkLibrary.Inventory && s.LinkId==carriedLink.Id);
            var destinationSlot=Descendants(panel!).OfType<ChestSlot>().First(s=>s.Container=="projects");
            var dragData=new Godot.Collections.Dictionary {["path"]=carriedLink.Path,["link"]=carriedLink.Id,["container"]=LinkLibrary.Inventory};
            Check(destinationSlot._CanDropData(Vector2.Zero,dragData),"Chest accepts a file dragged from carried inventory");
            destinationSlot._DropData(Vector2.Zero,dragData);
            Check(carriedLink.ChestId=="projects" && files.Exists(carriedLink.Path),"Dragging stores the link in another chest without moving the file");
            library.Transfer(carriedLink.Id, "inbox");
            ShowChest("inbox"); await Frames(30);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "inventory.png"));
            Descendants(panel!).OfType<Button>().Single(b=>b.Name=="ChestNextPage").EmitSignal(Godot.Button.SignalName.Pressed);await Frames(20);
            Check(pageIndex==1 && Descendants(panel!).OfType<Label>().Any(l=>l.Name=="ChestPageNumber" && l.Text=="2/3"),"Arrow inside chest advances to page two and updates its page indicator");
            Descendants(panel!).OfType<Button>().Single(b=>b.Name=="ChestNextPage").EmitSignal(Godot.Button.SignalName.Pressed);await Frames(20);
            Check(pageIndex==2 && Descendants(panel!).OfType<Button>().Single(b=>b.Name=="ChestNextPage").Disabled,"Chest arrow reaches page three and stops at the last page");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"chest-page-three.png"));
            Check(pageIndex == 2, "Inventory supports multiple pages");
            ShowChestPage("inbox", nested, 0); await Frames(20);
            Check(folderPath == nested, "Nested folder view stays inside cave");
            Descendants(panel!).OfType<Button>().Single(b=>b.Name=="FolderBack").EmitSignal(Godot.Button.SignalName.Pressed);await Frames(12);
            Check(folderPath==null,"Back returns from a folder to its chest");
            Descendants(panel!).OfType<Button>().Single(b=>b.Name=="FolderForward").EmitSignal(Godot.Button.SignalName.Pressed);await Frames(12);
            Check(folderPath==nested,"Forward restores the browsed folder");
            Descendants(panel!).OfType<LineEdit>().Single(e=>e.Name=="FolderAddress").EmitSignal(LineEdit.SignalName.TextSubmitted,System.IO.Path.Combine(nested,"Inside.txt"));await Frames(15);
            Check(FileService.Normalize(folderPath!)==FileService.Normalize(nested) && chestQuery=="Inside.txt" && Descendants(panel!).OfType<ChestSlot>().Any(s=>s.Entry?.Name=="Inside.txt"),"A file path navigates to its folder and finds the file");
            var file = state.Links.First(l => l.Name == "Document 00.txt"); library.Transfer(file.Id, LinkLibrary.Inventory); Changed();
            Check(store.Load().Links.Any(l => l.Id == file.Id && l.ChestId == LinkLibrary.Inventory), "Carried link persists");
            ShowChest("inbox"); await Frames(12);
            var heldSlot = Descendants(panel!).OfType<ChestSlot>().First(s => s.Entry != null);
            var originalContainer = state.Links.Single(l => l.Id == heldSlot.LinkId).ChestId;
            heldSlot.Activated!(MouseButton.Left, false, false);
            _Input(new InputEventKey { Keycode = Key.Escape, Pressed = true });
            Check(panel == null && openedChest == null && walking && Input.MouseMode == Input.MouseModeEnum.Captured, "Escape in a chest closes it and resumes walking");
            Check(heldItem == null && state.Links.Single(l => l.Id == heldSlot.LinkId).ChestId == originalContainer, "Closing a chest cancels pickup without moving the link");
            _Input(new InputEventKey { Keycode = Key.Escape, Pressed = true, Echo = true });
            Check(walking, "Holding Escape does not release the cave through key repeat");
            await Frames(30);
            Check(Math.Abs(lids["inbox"].Rotation.X) < .1f, "Chest lid closes while the cave stays active");
            _Input(new InputEventKey { Keycode = Key.Escape, Pressed = false });
            _Input(new InputEventKey { Keycode = Key.Escape, Pressed = true });UpdateEscape(.25f);
            Check(walking, "A quick Escape tap while walking keeps the cave active");
            _Input(new InputEventKey {Keycode=Key.Escape,Pressed=false});UpdateEscape(1);
            Check(walking, "Releasing Escape cancels exit progress");
            _Input(new InputEventKey {Keycode=Key.Escape,Pressed=true});UpdateEscape(.9f);
            Check(!walking && Input.MouseMode == Input.MouseModeEnum.Visible, "Holding Escape returns the mouse to Windows");
            _Input(new InputEventKey {Keycode=Key.Escape,Pressed=false});
            ShowSettings(); await Frames(5);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "settings.png"));
            _Input(new InputEventKey { Keycode = Key.Escape, Pressed = true });
            Check(panel == null && walking && Input.MouseMode == Input.MouseModeEnum.Captured, "Escape closes settings and resumes walking");
            StartWalking();
            player.Position=new Vector3(2,.1f,3);player.Rotation=Vector3.Zero;camera.Rotation=Vector3.Zero;flying=false;await Frames(8);
            float yaw = player.Rotation.Y;
            _UnhandledInput(new InputEventMouseMotion { Relative = new Vector2(40, 0) });
            Check(player.Rotation.Y != yaw, "Mouse look changes yaw");
            var beforeWalk = player.Position;
            Input.ParseInputEvent(new InputEventKey { PhysicalKeycode = Key.W, Keycode = Key.W, Pressed = true });
            await Frames(25);
            Input.ParseInputEvent(new InputEventKey { PhysicalKeycode = Key.W, Keycode = Key.W, Pressed = false });
            Check(player.Position.DistanceTo(beforeWalk) > .3f, "W key moves the player through physics");
            Input.ParseInputEvent(new InputEventKey { PhysicalKeycode = Key.Space, Keycode = Key.Space, Pressed = true });
            await Frames(8);
            Input.ParseInputEvent(new InputEventKey { PhysicalKeycode = Key.Space, Keycode = Key.Space, Pressed = false });
            Check(player.Position.Y > .2f, "Space jumps off the floor");
            await Frames(90);
            results.Add("Walking FPS sampled: " + Engine.GetFramesPerSecond());
            Release();
            Check(Input.MouseMode == Input.MouseModeEnum.Visible, "Release restores visible cursor");
            BeginPlacement("barrel", null); placementPosition = new Vector3(2, 0, -2); placementValid = true;
            int before = state.BuildingBlocks.Count;var stableWorld=world;int entriesBefore=enterRequests;Place();
            Check(world==stableWorld && enterRequests==entriesBefore && walking,"Placing blocks preserves world and active window without re-entering");
            Check(state.BuildingBlocks.Count == before + 1, "Decoration placement persists");
            CancelPlacement();
            var packed = state.Chests.Single(c => c.Id == "inbox");
            ShowChest("inbox"); await Frames(5);
            var title = Descendants(panel!).OfType<LineEdit>().Single(e => e.Name == "ChestName");
            title.Text = "My files ü"; title.EmitSignal(LineEdit.SignalName.TextSubmitted, title.Text);
            Check(packed.Name == "My files ü", "Click-to-edit chest title commits a Unicode name");
            ClosePanelAndResume();
            var chestLinks = state.Links.Where(l => l.ChestId == packed.Id).Select(l => l.Id).Order().ToArray();
            hovered = packed.Id; UpdateBreaking(.5f, true);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"mining.png"));
            Check(crackStage >= 0 && cracks is {Visible:true}, "Mining displays vanilla crack stages on the target");
            Check(!packed.Carried, "A short left hold does not break a chest");
            UpdateBreaking(.1f, false); Check(crackStage == -1 && cracks is {Visible:false}, "Releasing mining removes crack overlay"); hovered = packed.Id; UpdateBreaking(.8f, true);
            Check(!packed.Carried, "Releasing left-click resets breaking progress");
            UpdateBreaking(.5f, true);
            Check(packed.Carried && !chestNodes.ContainsKey(packed.Id), "Holding left-click packs the chest and removes it from the cave");
            Check(chestLinks.SequenceEqual(state.Links.Where(l => l.ChestId == packed.Id).Select(l => l.Id).Order()), "Packed chest retains every file link");
            var savedPacked = store.Load();
            Check(savedPacked.Chests.Single(c => c.Id == packed.Id).Carried && savedPacked.Chests.Single(c => c.Id == packed.Id).Name == "My files ü", "Packed chest and name survive save/load");
            Check(store.Load().Drops.Any(d => d.ItemId == packed.Id), "Uncollected named chest drop survives save/load");
            Check(state.Drops.Any(d => d.ItemId == packed.Id) && !SupplyItems().Any(i => i.Id == packed.Id), "Broken chest becomes a saved world drop instead of instant inventory");
            var chestDrop = state.Drops.Single(d => d.ItemId == packed.Id);
            player.Position = dropNodes[chestDrop.Id].Body.Position - Vector3.Up * .5f; UpdateDrops(.7f);
            Check(!state.Drops.Any(d => d.ItemId == packed.Id) && SupplyItems().Any(i => i.Id == packed.Id), "Walking over dropped chest collects its original identity");
            ShowBuildingInventory(); await Frames(12);
            Check(Descendants(panel!).OfType<ChestSlot>().Any(s => s.TooltipText.Contains("My files ü")), "Packed named chest is visible in building inventory");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "building-inventory.png"));
            BeginPlacement("chest", packed.Id); placementPosition = new Vector3(0, 0, -3); placementValid = true; Place();
            Check(!packed.Carried && packed.Name == "My files ü" && chestNodes.ContainsKey(packed.Id) && chestLinks.SequenceEqual(state.Links.Where(l => l.ChestId == packed.Id).Select(l => l.Id).Order()), "Placing a packed chest restores its name and contents");
            player.Position = new Vector3(2, .1f, 3); player.Rotation = Vector3.Zero; camera.Rotation = new Vector3(-.6f, 0, 0);
            await Frames(8);
            player.Rotation=Vector3.Zero;camera.Rotation=new Vector3(-.6f,0,0);
            BeginPlacement("stone", null); UpdatePlacement();
            results.Add($"Floor placement valid={placementValid}, target={placementPosition}, player={player.Position}, camera={camera.Rotation}");
            Check(placementValid && placementPosition.Y == 0, "Ray placement finds clear floor without intersecting its supporting block");
            Place(); CancelPlacement(); await Frames(3);
            var floorBlock = state.BuildingBlocks.Last();
            player.Position = new Vector3(floorBlock.X, 1.2f, floorBlock.Z + 3); camera.LookAt(new Vector3(floorBlock.X, floorBlock.Y + 1, floorBlock.Z), Vector3.Up);
            BeginPlacement("stone", null); UpdatePlacement();
            Check(placementValid && placementPosition.Y >= 1, "Ray placement supports stacking blocks on an existing block");
            CancelPlacement();
            int stoneCount = state.Supplies["stone"];
            BeginPlacement("stone", null); placementPosition = new Vector3(2, 0, 0); placementValid = true; Place(); CancelPlacement();
            var placedBlock = state.BuildingBlocks.Last();
            Check(state.Supplies["stone"] == stoneCount - 1 && store.Load().BuildingBlocks.Any(b => b.Id == placedBlock.Id), "Placing a building block consumes one supply and persists");
            hovered = "$block:" + placedBlock.Id; UpdateBreaking(1, true);
            Check(state.Supplies["stone"] == stoneCount - 1 && state.Drops.Any(d => d.Kind == "stone"), "Mined block waits in world as a miniature pickup");
            foreach(var d in state.Drops.Where(d => d.Kind == "stone").ToArray()) CollectDrop(d);
            Check(!state.BuildingBlocks.Any(b => b.Id == placedBlock.Id) && state.Supplies["stone"] == stoneCount, "Breaking a placed block returns it to inventory");
            var terrainKey = terrain.First(t => t.Value.Kind == "stone").Key;
            hovered = "$terrain:" + terrainKey; UpdateBreaking(1, true);
            foreach(var d in state.Drops.Where(d => d.Kind == "stone").ToArray()) CollectDrop(d);
            Check(!terrain.ContainsKey(terrainKey) && state.RemovedTerrain.Contains(terrainKey) && state.Supplies["stone"] == stoneCount + 1, "Cave terrain can be mined and collected");
            Check(store.Load().RemovedTerrain.Contains(terrainKey), "Mined terrain stays removed across save/load");
            ShowBuildingInventory(); await Frames(8);
            Check(Descendants(panel!).OfType<ChestSlot>().Count() == 36, "Vanilla inventory has 27 storage and 9 hotbar slots");
            var reverseSource=Descendants(panel!).OfType<ChestSlot>().First(s=>s.Name.ToString().StartsWith("InventoryHotbar") && s.BuildKey!=null);
            var reverseTarget=Descendants(panel!).OfType<ChestSlot>().First(s=>s.Name.ToString().StartsWith("InventoryStorage") && s.BuildKey!=null && s.BuildKey!=reverseSource.BuildKey);
            var sourceKey=reverseSource.BuildKey;var targetKey=reverseTarget.BuildKey;int sourceCount=reverseSource.Count,targetCount=reverseTarget.Count;
            var start=reverseSource.GetGlobalRect().GetCenter();var end=reverseTarget.GetGlobalRect().GetCenter();
            GetViewport().PushInput(new InputEventMouseMotion {Position=start,GlobalPosition=start},true);
            GetViewport().PushInput(new InputEventMouseButton {Position=start,GlobalPosition=start,ButtonIndex=MouseButton.Left,Pressed=true,ButtonMask=MouseButtonMask.Left},true);await Frames(2);
            GetViewport().PushInput(new InputEventMouseMotion {Position=end,GlobalPosition=end,Relative=end-start,ButtonMask=MouseButtonMask.Left},true);await Frames(3);
            GetViewport().PushInput(new InputEventMouseButton {Position=end,GlobalPosition=end,ButtonIndex=MouseButton.Left,Pressed=false},true);await Frames(3);
            Check(reverseSource.BuildKey==targetKey && reverseTarget.BuildKey==sourceKey && reverseSource.Count==targetCount && reverseTarget.Count==sourceCount,"Dragging hotbar to occupied inventory swaps both visible icons and counts immediately");
            Save();Check(store.Load().Hotbar.SequenceEqual(state.Hotbar),"Reverse hotbar swap persists");

            var destination = Descendants(panel!).OfType<ChestSlot>().Last(); destination.BuildDropped!("brick");
            Check(state.Hotbar[8] == "brick" && store.Load().Hotbar[8] == "brick", "Dragging a block onto hotbar persists its binding");
            ClosePanelAndResume(); SelectHotbar(8);
            Check(placingKind == "brick" && state.SelectedSlot == 8, "Hotbar selects equipped block");
            _UnhandledInput(new InputEventMouseButton {ButtonIndex=MouseButton.WheelDown,Pressed=true});
            Check(state.SelectedSlot == 0, "Mouse wheel cycles hotbar with wrapping");
            await Frames(8);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"hotbar.png"));
            BeginPlacement("stone", null);placementPosition=new Vector3(3,0,-1);placementValid=true;Place();CancelPlacement();
            player.Position=new Vector3(3,.1f,2);player.Rotation=Vector3.Zero;camera.LookAt(new Vector3(3,.5f,-1));
            await Frames(4);
            player.Rotation=Vector3.Zero;camera.LookAt(new Vector3(3,.5f,-1));
            Input.ParseInputEvent(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=true});
            await Frames(12);
            results.Add($"Mining target={hovered} walking={walking} hidden={hidden} panel={panel!=null}");
            Check(cracks is {Visible:true}, "Live mouse hold renders crack animation");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"mining.png"));
            await Frames(60);
            Input.ParseInputEvent(new InputEventMouseButton {ButtonIndex=MouseButton.Left,Pressed=false});
            await Frames(4);
            Check(state.Drops.Count>0 && dropNodes.Count>0, "Finished live mining leaves a spinning miniature in the world");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"drops.png"));
            ShowChest(packed.Id); await Frames(15);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "renamed-chest.png"));
            Release(); ShowMusic(); await Frames(5);
            Check(panel != null, "Jukebox interface opens");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output, "jukebox.png"));
            ClosePanel();
            Check(System.IO.File.ReadAllText(file.Path) == "fixture", "Source fixture is unchanged after UI organization");
            Check(effects.Count == 8 && effects["open"] is AudioStreamOggVorbis && effects["pickup"] is AudioStreamOggVorbis, "Minecraft sound effects load");
            var wav = System.IO.Path.Combine(source, "test-music.wav");
            System.IO.File.WriteAllBytes(wav, Godot.FileAccess.GetFileAsBytes("res://Assets/Audio/ambience.wav"));
            state.Settings.Playlist = [wav]; state.Settings.MusicEnabled = true; PlayTrack();
            Check(music.Playing, "User-supplied WAV playback starts");
            await Frames(3);locked = true; UpdateAudio();await Frames(2); Check(music.StreamPaused && ambience.StreamPaused, "Session lock pauses all audio"); locked = false;
            ClosePanel();CancelPlacement();StartWalking();
            player.Position=new Vector3(0,.05f,-5);player.Rotation=Vector3.Zero;camera.LookAt(new Vector3(0,-2,-25));
            Check(windowGlassCount==56 && rainColumnCount>0,"Glass opening looks onto an outdoor rain scene");
            await Frames(20);
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"rain-lookout.png"));
            player.Position=new Vector3(4.5f,.05f,-2);camera.LookAt(new Vector3(6,-.125f,-4));await Frames(12);
            Check(Descendants(world).OfType<MeshInstance3D>().Any(n=>n.MaterialOverride==waterMaterial) && water.Cells.ContainsKey(new(6,-1,-4)) && !water.Cells.ContainsKey(new(6,-1,6)),"Animated water occupies the recessed stream channel");
            GetViewport().GetTexture().GetImage().SavePng(System.IO.Path.Combine(output,"water.png"));
            var bankKey="5,-0.5,-4";
            state.RemovedTerrain.Add(bankKey);BuildWorld();
            for(int tick=0;tick<12;tick++) UpdateWater(.21f);
            Check(water.Cells.ContainsKey(new(5,-1,-4)),"Mining the stream bank fills the excavated block with water");
            var dam=new BuildingBlock {Kind="stone",X=5,Y=-1,Z=-4};state.BuildingBlocks.Add(dam);CreateBuildingBlock(dam);
            for(int tick=0;tick<12;tick++) UpdateWater(.21f);
            Check(!water.Cells.ContainsKey(new(5,-1,-4)),"Placing a block displaces flowing water");
            state.BuildingBlocks.Remove(dam);state.RemovedTerrain.Remove(bankKey);BuildWorld();
            ShowSearch();await Frames(4);
            Check(Descendants(panel!).OfType<Label>().Any(l=>l.Text.Contains("matches · Page 1 of")),"File search shows total matches and pages");
            Descendants(panel!).OfType<Button>().Single(b=>b.Text=="Next").EmitSignal(Godot.Button.SignalName.Pressed);
            Check(Descendants(panel!).OfType<Label>().Any(l=>l.Text.Contains("Page 2 of")),"File search can reach results beyond the first ten");
            results.Add("Rendering FPS sampled: " + Engine.GetFramesPerSecond());
            System.IO.File.WriteAllLines(System.IO.Path.Combine(output, "results.txt"), results);
            Save(); await Frames(4); GC.Collect(); GC.WaitForPendingFinalizers();
            GetTree().Quit(results.Any(r => r.StartsWith("FAIL")) ? 1 : 0);
        }
        catch (Exception e) { GD.PushError(e.ToString()); System.IO.File.WriteAllText(System.IO.Path.Combine(output, "failure.txt"), e.ToString()); GetTree().Quit(1); }
    }
    private IEnumerable<Node> Descendants(Node node)
    { foreach (var child in node.GetChildren()) { yield return child; foreach (var sub in Descendants(child)) yield return sub; } }
}
